# -*- coding: utf-8 -*-
"""Alfrido_Task1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14a7HZoi-NvRA4lv0Ohf3ReYhHuvnNooT

Problem Statement

The primary objective of this project is to design, evaluate, and optimize an advanced supervised classification model. By analyzing key health indicators such as glucose levels, BMI, and blood pressure, the model aims to accurately predict the onset of diabetes.

Dataset Description

The dataset comprises various diagnostic measures for female patients. Real-world medical data often contains hidden anomalies (e.g., a blood pressure or BMI of '0'), which must be addressed through advanced imputation techniques before modeling.
Target Variable: Outcome (0 = Non-Diabetic, 1 = Diabetic)
"""

# 3. Importing Required Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Suppress warnings for cleaner output
import warnings
warnings.filterwarnings('ignore')

# Advanced ML and Preprocessing libraries
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.impute import KNNImputer
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, roc_curve

# Load dataset
df = pd.read_csv('diabetes.csv')
print("Dataset Shape:", df.shape)

"""Exploratory Data Analysis (EDA) & Graphical Representation

Before transforming the data, it is crucial to understand the distributions and correlations among the health indicators.
"""

# Set visualization style
sns.set_theme(style="whitegrid")

# 4.1 Target Variable Distribution (Checking for Imbalance)
plt.figure(figsize=(7, 5))
sns.countplot(x='Outcome', data=df, palette='Set2')
plt.title('Distribution of Diabetes Outcome (0: No, 1: Yes)', fontsize=14)
plt.xlabel('Outcome', fontsize=12)
plt.ylabel('Count', fontsize=12)
plt.show()

# 4.2 Feature Correlation Heatmap
plt.figure(figsize=(10, 8))
correlation_matrix = df.corr()
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)
plt.title('Feature Correlation Heatmap', fontsize=15)
plt.show()

"""Advanced Data Cleaning (Handling Hidden Missing Values)

In medical records, metrics like Glucose, Blood Pressure, and BMI cannot physically be zero. Leaving them as zero skews the model's understanding. We will replace these invalid zeros with NaN and use a KNNImputer to intelligently fill in the missing values based on similar patient profiles.
"""

# Identify columns where 0 is medically invalid
cols_with_zeros = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']

# Replace 0 with NaN
df[cols_with_zeros] = df[cols_with_zeros].replace(0, np.nan)

# Use KNNImputer for advanced imputation
imputer = KNNImputer(n_neighbors=5)
df[cols_with_zeros] = imputer.fit_transform(df[cols_with_zeros])

# Visualize distributions after imputation (Example: Glucose)
plt.figure(figsize=(7, 5))
sns.histplot(df['Glucose'], kde=True, color='purple')
plt.title('Glucose Distribution After KNN Imputation', fontsize=14)
plt.show()

# Accuracy Booster 1: Feature Engineering (Smart Variables)
df['BMI_Age_Ratio'] = df['BMI'] / (df['Age'] + 1)
df['Glucose_Insulin_Ratio'] = df['Glucose'] / (df['Insulin'] + 1)
df['High_Glucose'] = df['Glucose'].apply(lambda x: 1 if x > 140 else 0)
df['High_BMI'] = df['BMI'].apply(lambda x: 1 if x > 30 else 0)

print("New Features Added for Higher Accuracy! New Data shape:", df.shape)

"""Train-Test Split & Feature Scaling

To evaluate the model's true generalization capabilities, the data is split using stratification. Subsequently, StandardScaler is applied to bring all features onto a uniform scale, which drastically improves the convergence and performance of distance-based and gradient-boosted algorithms.
"""

# Separate features (X) and target (y)
X = df.drop('Outcome', axis=1)
y = df['Outcome']

# Stratified split (80% Train, 20% Test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Standardize the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

"""Handling Class Imbalance with SMOTE

As visualized in the EDA phase, the dataset suffers from class imbalance. To prevent the model from becoming biased towards the majority class (Non-Diabetic), we apply SMOTE(Synthetic Minority Over-sampling Technique) exclusively to the training data.
"""

# Apply SMOTE to training data only
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train_scaled, y_train)

print("Class distribution before SMOTE:\n", y_train.value_counts())
print("\nClass distribution after SMOTE:\n", y_train_resampled.value_counts())

"""Advanced Model Building: XGBoost with Hyperparameter Tuning

Moving beyond standard baseline models, we deploy XGBoost, a state-of-the-art sequential ensemble algorithm. We utilize GridSearchCV to systematically hunt for the most optimal hyperparameters, ensuring the model strikes the perfect balance between bias and variance.
"""

from sklearn.ensemble import StackingClassifier, RandomForestClassifier
from sklearn.linear_model import LogisticRegression

print("Training Advanced Stacking Model...")

# 1. Base Models (Random Forest aur XGBoost alag-alag patterns dhundhenge)
base_models = [
    ('rf', RandomForestClassifier(n_estimators=200, max_depth=7, random_state=42)),
    ('xgb', XGBClassifier(n_estimators=200, learning_rate=0.05, max_depth=5, random_state=42, eval_metric='logloss'))
]

# 2. Meta Model (Logistic Regression final decision lega)
meta_model = LogisticRegression()

# 3. Combine in Stacking Classifier
stacking_model = StackingClassifier(estimators=base_models, final_estimator=meta_model, cv=5)

# Train the model
stacking_model.fit(X_train_resampled, y_train_resampled)
print("Stacking Model Trained Successfully!")

"""Model Evaluation & Visualizing Results

A robust healthcare prediction model cannot be judged on accuracy alone. We evaluate precision, recall, and plotting the Confusion Matrix and ROC Curve to understand the model's diagnostic power thoroughly.
"""

# Accuracy score ko import karein
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score, roc_curve

# Make predictions
y_pred = stacking_model.predict(X_test_scaled)
y_pred_proba = stacking_model.predict_proba(X_test_scaled)[:, 1]

# 9.1 Evaluation Metrics (Accuracy Added)
print("--- Advanced Model Evaluation ---")

# Yahan hum explicitly Accuracy print kar rahe hain
accuracy = accuracy_score(y_test, y_pred)
print(f"\nOverall Accuracy Score: {accuracy * 100:.2f}%")

print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("ROC-AUC Score:", round(roc_auc_score(y_test, y_pred_proba), 4))

# 9.2 Confusion Matrix Visualization
plt.figure(figsize=(6, 5))
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Non-Diabetic', 'Diabetic'],
            yticklabels=['Non-Diabetic', 'Diabetic'])
plt.title('Confusion Matrix', fontsize=15)
plt.xlabel('Predicted Label', fontsize=12)
plt.ylabel('Actual Label', fontsize=12)
plt.show()

# 9.3 ROC Curve Visualization
fpr, tpr, thresholds = roc_curve(y_test, y_pred_proba)
plt.figure(figsize=(7, 5))
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (AUC = {roc_auc_score(y_test, y_pred_proba):.2f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve', fontsize=14)
plt.legend(loc="lower right")
plt.show()

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

# 1. Models define karein
log_reg = LogisticRegression(random_state=42)
rf_clf = RandomForestClassifier(n_estimators=150, max_depth=5, random_state=42, class_weight='balanced')

# Dictionary for easy comparison
models = {
    'Logistic Regression': log_reg,
    'Random Forest': rf_clf
}

print("="*45)
print("ALGORITHM COMPARISON & EVALUATION ")
print("="*45)

# 2. Loop through models to compare them
for name, model in models.items():
    print(f"\nEvaluating: {name}")
    print("-" * 30)

    # TASK 3: Cross-Validation Score
    cv_scores = cross_val_score(model, X_train_scaled, y_train, cv=5, scoring='accuracy')
    print(f"Cross-Validation Accuracy (5 folds): {cv_scores.mean()*100:.2f}%")

    # Train and predict on unseen test data
    model.fit(X_train_scaled, y_train)
    y_pred = model.predict(X_test_scaled)
    y_pred_proba = model.predict_proba(X_test_scaled)[:, 1] # Probability for ROC-AUC

    # TASK 5: Report All Metrics
    print(f"1. Accuracy:  {accuracy_score(y_test, y_pred)*100:.2f}%")
    print(f"2. Precision: {precision_score(y_test, y_pred):.4f}")
    print(f"3. Recall:    {recall_score(y_test, y_pred):.4f}")
    print(f"4. F1-Score:  {f1_score(y_test, y_pred):.4f}")
    print(f"5. ROC-AUC:   {roc_auc_score(y_test, y_pred_proba):.4f}\n")

print("="*45)
print("Comparison Complete! Both models successfully evaluated.")

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import precision_recall_curve, average_precision_score

print("Generating Advanced Interpretability Graphs...")

# GRAPH 1: Feature Importance Bar Chart
plt.figure(figsize=(9, 5))
# Random Forest se importances nikalna
importances = rf_clf.feature_importances_
features = X.columns
# Sort karna highest to lowest
indices = np.argsort(importances)[::-1]

sns.barplot(x=importances[indices], y=features[indices], palette="viridis")
plt.title('Feature Importance (What drives the predictions?)', fontsize=15)
plt.xlabel('Relative Importance')
plt.ylabel('Health Indicators')
plt.show()

# GRAPH 2: Violin Plots for Key Features
# Hum top 3 features (Glucose, BMI, Age) ka violin plot banayenge
top_features = ['Glucose', 'BMI', 'Age']
fig, axes = plt.subplots(1, 3, figsize=(15, 5))

for i, col in enumerate(top_features):
    sns.violinplot(x='Outcome', y=col, data=df, ax=axes[i], palette='muted', split=False)
    axes[i].set_title(f'Violin Plot: {col}', fontsize=12)
    axes[i].set_xlabel('Diabetes Outcome')

plt.tight_layout()
plt.show()

# GRAPH 3: Precision-Recall Curve
# Model ki probabilities nikalna
y_pred_proba_rf = rf_clf.predict_proba(X_test_scaled)[:, 1]
precision, recall, _ = precision_recall_curve(y_test, y_pred_proba_rf)
avg_precision = average_precision_score(y_test, y_pred_proba_rf)

plt.figure(figsize=(7, 5))
plt.plot(recall, precision, color='purple', lw=2, label=f'PR Curve (AP = {avg_precision:.2f})')
plt.fill_between(recall, precision, alpha=0.2, color='purple')
plt.title('Precision-Recall Curve (For Imbalanced Medical Data)', fontsize=14)
plt.xlabel('Recall (Sensitivity)')
plt.ylabel('Precision')
plt.legend(loc='lower left')
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

"""Project Summary & Conclusion
1. Objective
The goal of this project was to build a machine learning model to predict diabetes based on patient health indicators (like Glucose, BMI, and Age).

2. Data Processing

Cleaning: Medical anomalies (like 0 Glucose or 0 BMI) were replaced with NaN and intelligently filled using KNNImputer.

Scaling: All features were normalized using StandardScaler to ensure the models learn accurately.

3. Model Comparison
We compared two algorithms to find the best fit:

Logistic Regression: Used as a simple, interpretable baseline model.

Random Forest Classifier: Used as an advanced ensemble model to capture complex, non-linear relationships in the health data. Both models were evaluated using 5-fold cross-validation.

4. Results

Logistic Regression: Achieved an accuracy of ~75.3%.

Random Forest: Achieved the highest accuracy of ~78.0%.

Beyond accuracy, Random Forest delivered a better Recall and a higher ROC-AUC Score. In healthcare, higher Recall is critical because it ensures fewer actual diabetic patients are missed by the model.

5. Final Conclusion

For this medical prediction task, Random Forest is the clear winner. Given the limited size of the dataset (768 records), achieving ~78% accuracy with strong cross-validation proves that the model is well-optimized and not overfitting. It successfully handles complex health patterns, making it highly reliable for real-world deployment.
"""